# Generated by Django 3.0 on 2019-12-03 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique_for_date='pub_date')),
                ('body', models.TextField(help_text='Use Markdown to mark this up. http://daringfireball.net/projects/markdown/syntax')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_blog.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_blog.Category')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-pub_date'],
            },
        ),
    ]
